maps/de_mariobros.res
models/de_mariobros/mariobros.mdl
sound/de_mariobros/mario_clear.wav
sound/de_mariobros/mario_dead.wav
sound/de_mariobros/mario_egold.wav
sound/de_mariobros/mario_ground.wav
sound/de_mariobros/mario_totube.wav
gfx/env/mariobrosbk.tga
gfx/env/mariobrosdn.tga
gfx/env/mariobrosft.tga
gfx/env/mariobroslf.tga
gfx/env/mariobrosrt.tga
gfx/env/mariobrosup.tga
