models/de_construction_2011/fork.mdl
models/de_construction_2011/kotushka.mdl
models/de_construction_2011/scaffolding.mdl
models/de_construction_2011/tir_truck.mdl
gfx/env/pochmurnieBK.tga
gfx/env/pochmurnieDN.tga
gfx/env/pochmurnieFT.tga
gfx/env/pochmurnieLF.tga
gfx/env/pochmurnieRT.tga
gfx/env/pochmurnieUP.tga