gfx/env/hpup.tga
gfx/env/hpdn.tga
gfx/env/hplf.tga
gfx/env/hprt.tga
gfx/env/hpft.tga
gfx/env/hpbk.tga
models/hkcdc/sign.mdl
models/hkcdc/tree1.mdl
models/hkcdc/tree1b.mdl
models/hkcdc/sunys.mdl
models/hkcdc/b1.mdl
models/hkcdc/b2.mdl
models/hkcdc/b4.mdl
models/hkcdc/b3.mdl
models/hkcdc/top.mdl
models/hkcdc/tree2.mdl
models/hkcdc/side4.mdl
models/hkcdc/side3.mdl
sprites/hkcdc/spr1.spr
models/hkcdc/light2.mdl
models/hkcdc/sunys2b.mdl
models/hkcdc/roofa.mdl
models/hkcdc/roofb.mdl
models/hkcdc/roofc.mdl
models/hkcdc/boat.mdl
models/hkcdc/chair.mdl
models/hkcdc/light.mdl
models/hkcdc/side2.mdl
models/hkcdc/side.mdl
models/hkcdc/propsc.mdl
models/hkcdc/propsb.mdl
models/hkcdc/bullet.mdl
models/hkcdc/propsd.mdl
models/hkcdc/b5b.mdl
models/hkcdc/propsa.mdl
models/hkcdc/b5c.mdl
models/hkcdc/chair2.mdl
models/hkcdc/ow.mdl
models/hkcdc/ow2.mdl
overviews/de_hp_npm.txt
overviews/de_hp_npm.bmp
