homersimpson.wad
gfx/env/simpsonsup.tga
gfx/env/simpsonsdn.tga
gfx/env/simpsonslf.tga
gfx/env/simpsonsrt.tga
gfx/env/simpsonsft.tga
gfx/env/simpsonsbk.tga
sound/de_homersimpson/burp.wav
sound/de_homersimpson/dieu2.wav
sound/de_homersimpson/cloche.wav
sound/de_homersimpson/krusty.wav
sound/de_homersimpson/haha.wav
sound/de_homersimpson/sonnette.wav
sound/de_homersimpson/bourre.wav
sound/de_homersimpson/spidercochon.wav
sound/de_homersimpson/policetalk.wav
sound/de_homersimpson/excellent.wav
sound/de_homersimpson/courageux.wav
sound/de_homersimpson/duff.wav
sound/de_homersimpson/lunettes.wav
sound/de_homersimpson/dormir.wav
sound/de_homersimpson/reproches.wav
sound/de_homersimpson/enfant.wav
sound/de_homersimpson/intro.wav
sound/de_homersimpson/yellow.wav
sound/de_homersimpson/coursfiston.wav
sound/de_homersimpson/rotormachine.wav
sound/de_homersimpson/3dmhills.wav
sound/de_homersimpson/drips.wav
overviews/de_homersimpsonv2.bmp
overviews/de_homersimpsonv2.txt

