//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zl_boss_oberon.html
sprites/3dmflared.spr
models/zl/npc/oberon/crane01.mdl
models/zl/npc/oberon/zl_sky.mdl
models/zl/npc/oberon/zl_galogramma.mdl
maps/zl_boss_oberon.bsp
