// zs_decoy.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (99):
gfx/env/decoybk.tga
gfx/env/decoydn.tga
gfx/env/decoyft.tga
gfx/env/decoylf.tga
gfx/env/decoyrt.tga
gfx/env/decoyup.tga
grid.wad
hs4.wad
models/ammo_box_set/w_556nato_big.mdl
models/ammo_box_set/w_556natobox.mdl
models/ammo_box_set/w_556natobox_big.mdl
models/ammo_box_set/w_9mmclip_big.mdl
models/ammo_box_set/w_shotbox_big.mdl
models/army1.mdl
models/army2.mdl
models/bigtree.mdl
models/c4_plastic_bomb.mdl
models/dynamite.mdl
models/dynamite_switch.mdl
models/fern.mdl
models/gibs_cave.mdl
models/gibs_decoy_pipe.mdl
models/gibs_metalplate.mdl
models/gibs_woodplank.mdl
models/grass2.mdl
models/grass3.mdl
models/grass4.mdl
models/grass5.mdl
models/helicopter_blackhawkdown.mdl
models/light.mdl
models/machine.mdl
models/pipe.mdl
models/pipe_1.mdl
models/pipe_2.mdl
models/pipe_4.mdl
models/pipe_5.mdl
models/player/sas/sas.mdl
models/pred_plant.mdl
models/props/bush_fern_small.mdl
models/props/bush_japan_fern_01.mdl
models/props/rock_japan_rocks2.mdl
models/rcontrolbomb_indicator.mdl
models/stone_all_1_mdl.mdl
models/stone_all_2_mdl.mdl
models/stone_all_3_mdl.mdl
models/stone_small.mdl
models/tire.mdl
models/tower.mdl
models/trace_barrel01.mdl
models/tracker.mdl
models/wakitoki.mdl
sound/ambience/Facility_03.wav
sound/ambience/Rain_2.wav
sound/ambience/Rain_3.wav
sound/ambience/Rain_4.wav
sound/ambience/the_horror1.wav
sound/ambience/the_horror3.wav
sound/ambience/thunder_clap.wav
sound/ambience/thunder_clap2.wav
sound/ambience/thunder_clap3.wav
sound/ambience/thunder_clap4.wav
sound/bgm/alamo_battle.wav
sound/bgm/alamo_success.wav
sound/bgm/downed_wakup.wav
sound/bgm/pipe_bomb.wav
sound/bgm/start.wav
sound/radio/com_followcom.wav
sound/voice/team2_surround.wav
sound/weapons/cartfrag.wav
sound/zombi/Human_Death_01.wav
sound/zombi/Human_Death_02.wav
sound/zs_culvert/dione_metamorphosis.wav
sound/zs_culvert/radiotone.wav
sound/zs_decoy/blitz.wav
sound/zs_decoy/culvert_bgm1.wav
sound/zs_decoy/culvert_bgm2.wav
sound/zs_decoy/culvert_dione_event.wav
sound/zs_decoy/hit_grass.wav
sound/zs_decoy/marsh_bgm1.wav
sound/zs_decoy/marsh_bgm2.wav
sound/zs_decoy/marsh_deadman.wav
sound/zs_decoy/mortar_call.wav
sound/zs_decoy/zs_decoy_intro.wav
sound/zs_trace/metal_door_slide.wav
sound/zs_trace/team_fx.wav
sprites/3dmflaora.spr
sprites/flame1.spr
sprites/flame2.spr
sprites/flame_burn01.spr
sprites/ledglow.spr
sprites/muzzleflash14.spr
sprites/smoke_ia.spr
tdm01.wad
zm_abyss3.wad
zm_tomb2.wad
zs_decoy.wad
zs_evolution.wad
zs_trace.wad
