# This is a basic workflow to help you get started with Actions

name: Sync to GitCode

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to GitCode
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        GITCODE_USERNAME_ENCODED=$(echo -n "${{ secrets.GITCODE_USERNAME }}" | jq -sRr @uri)
        GITCODE_PASSWORD_ENCODED=$(echo -n "${{ secrets.GITCODE_PASSWORD }}" | jq -sRr @uri)
        git remote add gitcode https://$GITCODE_USERNAME_ENCODED:$GITCODE_PASSWORD_ENCODED@gitcode.net/2301_79002849/cs16Resource.git
        git fetch gitcode main
        git rebase --strategy-option ours gitcode/main
        git push gitcode HEAD:main
        
    - name: List all files and folders
      run: |
        mkdir file_info
        find . -type f -exec sh -c 'echo "{ \"path\": \"{}\", \"name\": \"$(basename {})\", \"time\": \"$(git log -1 --format=%aI {} | xargs)\" }" > file_info/$(basename {}).json' \;
    - name: Combine JSON files into one
      run: |
        echo '[' > all_files.json
        find file_info -name "*.json" -exec cat {} \; | jq -c . >> all_files.json
        echo ']' >> all_files.json
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: all-files
        path: all_files.json
