# This is a basic workflow to help you get started with Actions

name: Sync to GitCode

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to GitCode
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git remote add gitcode https://${{ secrets.GITCODE_ID }}:${{ secrets.GITCODE_PW }}@gitcode.net/2301_79002849/cdn.git
        git push gitcode HEAD:d0
