name: Use edit.json in new workflow

on:
  workflow_run:
    workflows: ["Sync to GitCode"]
    types:
      - completed

jobs:
  use-edit-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: all-files

    - name: Do something with edit.json
      run: |
        # 在這裡添加你想用 edit.json 做的事情
        cat edit.json
